# Generated by Django 2.1 on 2018-09-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNum', models.CharField(max_length=255, unique=True)),
                ('numPlaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captainsName', models.CharField(max_length=255)),
                ('captainsSurname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airportsName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateTimeField()),
                ('arrivalTime', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Airplane')),
                ('arrivalAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='airport.Airport')),
                ('crew', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport.AirplaneCrew')),
                ('departureAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airport.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Passenger')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='airplanecrew',
            unique_together={('captainsName', 'captainsSurname')},
        ),
    ]
